# Makefile for Codinoc IDE
#
# Written by N.L.M. Nishshanke
#            M.P.M. Abeyrathne

SRC := cmd/dashboard.go \
			 cmd/database.go  \
			 cmd/domain.go    \
			 cmd/email.go     \
			 cmd/forgot.go    \
			 cmd/global.go    \
			 cmd/main.go      \
			 cmd/password.go  \
			 cmd/process.go   \
			 cmd/signin.go    \
			 cmd/signup.go

RUN:
	go run $(SRC)

BUILD:
	go build $(SRC)
	./codinoc